[project]
name = "coding-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "robertlane0", email = "robertlane0@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
coding-harness = "coding_harness:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
